# Generated by Django 4.1.7 on 2023-03-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=455, verbose_name='phone number:')),
                ('email', models.EmailField(max_length=442, verbose_name='email ')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(max_length=455, verbose_name='facebook ')),
                ('twitter', models.CharField(max_length=455, verbose_name='twitter ')),
                ('linkedin', models.CharField(max_length=455, verbose_name='linkedin ')),
                ('google_plus', models.CharField(max_length=455, verbose_name='google_plus ')),
            ],
            options={
                'verbose_name': 'social media account',
                'verbose_name_plural': 'socila media accounts',
            },
        ),
    ]
