# Generated by Django 4.1.7 on 2023-03-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_generalslider_generalslideractive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.CharField(max_length=44, verbose_name='money')),
                ('name', models.CharField(max_length=44, verbose_name='product name')),
                ('img', models.ImageField(upload_to='media', verbose_name='image')),
            ],
        ),
    ]
