# Generated by Django 4.1.7 on 2023-03-09 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_features_items'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='features_items',
            options={'verbose_name': 'features_items', 'verbose_name_plural': 'features_items'},
        ),
    ]
